version: '3'

services:
  python-app:
    container_name: python_log_app
    build: app/
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:12202
        tag: "app.fluent"
    networks:
      - elk
    depends_on:
      - fluentbit

  postgres:
    container_name: psql_db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - psql:/var/lib/postgresql/data
      - ./psql/prepare.sh:/docker-entrypoint-initdb.d/prepare.sh
    networks:
      - elk

  fluentbit:
    container_name: fluentbit
    image: fluent/fluent-bit
    links:
      - "postgres:db"
    ports:
      - 12202:12202/udp
      - 12202:12202    
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
    networks:
      - elk
    depends_on:
      - postgres

  grafana:
    container_name: grafana
    image: grafana/grafana:8.5.13
    links:
      - "postgres:db"
    ports:
      - 3000:3000
    networks:
      - elk
    depends_on:
      - postgres

networks:
  elk:
    driver: bridge
volumes:
  psql:


